### ISSUE TITLE
Warning about "key" props

### ISSUE THREAD

**Issue by kuon** [gcazaciuc/redux-fractal#4]
If I use `local` on child components, like this:

```typescript

import Child from "./child"

const Parent = (props) {
    const items = [<Child key="a" />, <Child key="b" />]
    return <div>{items}</div>
}

export default
local(...)(Parent)

// and child

const Child = (props) {
    return <div>child</div>
}

export default
local(...)(Child)



```

I have the following warning:

warning.js:40 Warning: UI: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

**Comment by gcazaciuc** [comment]
i believe this is react related. in react you cannot access a component key via props.key .Instead use another prop name, like id or so to pass a unique id and read it from props.

**Comment by kuon** [comment]
Yes it is react related. But I am not using or accessing `key` props, this is caused by using `local` on my component.

**Comment by gcazaciuc** [comment]
Can you paste the part generating the key in parent and child components ? I would like to see the
```js
local({
  key: (props) => ...
```
of both of the components.
Are you accesing somewhere in the app props.key ?

**Comment by gcazaciuc** [comment]
Anyhow i've made a change in `local` that prevents collisions with React key and published 1.3.1 ( no api changes, just an internal change).
Unless you're accessing props.key somewhere the issue should be fixed in 1.3.1

**Comment by kuon** [comment]
I still get the warning with 1.3.2.

My whole child component:

```typescript
import * as React from "react"
import * as classnames from "classnames"
import { bindActionCreators } from "redux"
import { local } from "redux-fractal"
import * as splitViewActions from "./ducks"


interface Props {
  horizontal?: boolean
  collapsible?: boolean
  toggleCollapsed?: (index: number) => void
  index?: number
}


const Separator =
local({
  key: (props, context) => context.splitViewId,
  mapDispatchToProps: (dispatch) => bindActionCreators(splitViewActions, dispatch)
})((props: Props) => {

  let klass = classnames("split-view-separator", {
    "-horizontal": props.horizontal,
    "-collapsible": props.collapsible
  })

  return (
    <div className={klass}
         onClick={() => {
           if (props.collapsible) {
             props.toggleCollapsed(props.index)
           }
         }}>
    </div>
  )
})

Separator.contextTypes.splitViewId = React.PropTypes.string

export default Separator

```

I tripled check my code, and there is no place when I access `.key` on props. And demoving the `local` call in my `Separator` removes the warning.

**Comment by gcazaciuc** [comment]
Alright, hopefully this t

**Comment by kuon** [comment]
Yeah, warning is  gone in 1.3.3, thanks.

**Comment by gcazaciuc** [comment]
Thank you to for raising this and valuable feedback!

**Comment by kuon** [comment]
Thanks to you for the quick response and a great library.
